In [1]:
import pandas as pd
import datetime as dt
import numpy as np

In [2]:
#load csv into dataframe
load_csv = ("../Source_Data/Police_Use_of_Force_Source_Data.csv")

In [3]:
source_data_df = pd.read_csv(load_csv)
source_data_df.head()

,X,Y,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,Is911Call,PrimaryOffense,SubjectInjury,ForceReportNumber,...,TotalCityCallsForYear,TotalPrecinctCallsForYear,TotalNeighborhoodCallsForYear,CenterGBSID,CenterLatitude,CenterLongitude,CenterX,CenterY,DateAdded,OBJECTID
0,-93.291183,45.018526,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,No,FLEEFT,Yes,1,...,322402,80434.0,4226,18266,45.018526,-93.291183,-10385126.96,5624438.454,2020/06/02 08:18:33+00,1
1,-93.265782,44.943185,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,No,FLEE,Yes,1,...,322402,84018.0,10923,11907,44.943185,-93.265782,-10382299.34,5612581.534,2020/06/02 08:18:33+00,2
2,-93.268029,44.979702,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,No,DISCON,No,1,...,322402,46998.0,23458,18612,44.979702,-93.268029,-10382549.52,5618326.520,2020/06/02 08:18:33+00,3
3,-93.271954,44.982469,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,No,DISCON,NaN,1,...,322402,46998.0,23458,17873,44.982469,-93.271954,-10382986.45,5618762.022,2020/06/02 08:18:33+00,4
4,-93.277025,44.978019,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,No,FLEE,Yes,3,...,322402,46998.0,23458,25506,44.978019,-93.277025,-10383550.97,5618061.726,2020/06/02 08:18:33+00,5

In [4]:
edited_source_data_df = source_data_df.drop(columns = {"X", "Y", "Is911Call", "ForceReportNumber",
                                  "SubjectRoleNumber", "TotalCityCallsForYear",
                                  "TotalPrecinctCallsForYear", "TotalNeighborhoodCallsForYear",
                                  "CenterGBSID", "CenterLatitude", "CenterLongitude",
                                  "CenterX", "CenterY", "DateAdded", "OBJECTID"})

edited_source_data_df.head(5)

,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,PrimaryOffense,SubjectInjury,SubjectRole,ForceType,ForceTypeAction,Race,Sex,EventAge,TypeOfResistance,Precinct,Neighborhood
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West

In [5]:
renamed_columns_df = edited_source_data_df.rename(columns={'PoliceUseOfForceID': 'police_use_of_force_id',
                                                          'CaseNumber': 'case_number', 'ResponseDate': 'response_date',
                                                          'PrimaryOffense': 'primary_offense', 'SubjectInjury': 'subject_injury',
                                                          'SubjectRole': 'subject_role', 'ForceType': 'police_use_of_force_type',
                                                          'ForceTypeAction': 'force_type_action', 'Race': 'subject_race', 
                                                          'Sex': 'subject_sex', 'EventAge': 'subject_age', 'TypeOfResistance': 'type_of_resistance',
                                                          'Problem': 'problem', 'Precinct': 'precinct', 'Neighborhood': 'neighborhood'})

renamed_columns_df.head(5)

,police_use_of_force_id,case_number,response_date,problem,primary_offense,subject_injury,subject_role,police_use_of_force_type,force_type_action,subject_race,subject_sex,subject_age,type_of_resistance,precinct,neighborhood
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West

In [6]:
renamed_columns_df["nbhd_key"] = ""

In [7]:
renamed_columns_df.head(5)

,police_use_of_force_id,case_number,response_date,problem,primary_offense,subject_injury,subject_role,police_use_of_force_type,force_type_action,subject_race,subject_sex,subject_age,type_of_resistance,precinct,neighborhood,nbhd_key
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley,
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central,
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West,
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West,
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West,

In [8]:
edited_renamed_columns_df = renamed_columns_df.rename(columns={'Precinct': 'precinct',
                                                               'Problem': 'problem',
                                                              'Neighborhood': 'neighborhood'})

In [9]:
edited_renamed_columns_df.head(5)

,police_use_of_force_id,case_number,response_date,problem,primary_offense,subject_injury,subject_role,police_use_of_force_type,force_type_action,subject_race,subject_sex,subject_age,type_of_resistance,precinct,neighborhood,nbhd_key
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley,
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central,
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West,
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West,
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West,

In [10]:
# Bring in Swati's MLPS_Neighborhoods.csv
load_second_csv = ("../target_files/MLPS_Neighborhoods.csv")
nbhd_keys_df = pd.read_csv(load_second_csv)
nbhd_keys_df.head(5)

   neighborhood_id          name  community_id
0                1      Armatage            10
1                2  East Harriet            10
2                3        Fulton            10
3                4         Kenny            10
4                5    King Field            10

In [11]:
nbhd_keys_df_edited = nbhd_keys_df.rename(columns={'NBHD_KEY': 'nbhd_key',
                                                  'name': 'neighborhood'})

In [12]:
nbhd_keys_df_edited.head(5)

   neighborhood_id  neighborhood  community_id
0                1      Armatage            10
1                2  East Harriet            10
2                3        Fulton            10
3                4         Kenny            10
4                5    King Field            10

In [13]:
left_join_df = pd.merge(edited_renamed_columns_df, nbhd_keys_df_edited, on = 'neighborhood', how= 'left')
left_join_df

,police_use_of_force_id,case_number,response_date,problem,primary_offense,subject_injury,subject_role,police_use_of_force_type,force_type_action,subject_race,subject_sex,subject_age,type_of_resistance,precinct,neighborhood,nbhd_key,neighborhood_id,community_id
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley,,NaN,NaN
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central,,25.0,9.0
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West,,73.0,3.0
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West,,73.0,3.0
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West,,73.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,20-Lynnhurst,2020/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Lynnhurst,,7.0,10.0
30050,11254283,12-St. Anthony East,2012/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,St. Anthony East,,NaN,NaN
30051,11254284,19-Columbia Park,2019/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Columbia Park,,NaN,NaN
30052,11254285,19-Kenwood,2019/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Kenwood,,36.0,1.0
30053,11254286,12-Cedar - Isles - Dean,2012/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Cedar - Isles - Dean,,33.0,1.0

In [14]:
left_join_df.drop(columns= {"nbhd_key"})

,police_use_of_force_id,case_number,response_date,problem,primary_offense,subject_injury,subject_role,police_use_of_force_type,force_type_action,subject_race,subject_sex,subject_age,type_of_resistance,precinct,neighborhood,neighborhood_id,community_id
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley,NaN,NaN
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central,25.0,9.0
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West,73.0,3.0
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West,73.0,3.0
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West,73.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,20-Lynnhurst,2020/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Lynnhurst,7.0,10.0
30050,11254283,12-St. Anthony East,2012/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,St. Anthony East,NaN,NaN
30051,11254284,19-Columbia Park,2019/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Columbia Park,NaN,NaN
30052,11254285,19-Kenwood,2019/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Kenwood,36.0,1.0
30053,11254286,12-Cedar - Isles - Dean,2012/01/01 00:00:00+00,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,Cedar - Isles - Dean,33.0,1.0

In [15]:
rearranged_df = left_join_df[['police_use_of_force_id','response_date',
                              'case_number','problem','subject_race',
                             'subject_sex', 'subject_age','subject_role', 'primary_offense',
                             'type_of_resistance', 'police_use_of_force_type',
                             'force_type_action', 'subject_injury', 'neighborhood_id',
                             'neighborhood', 'precinct']]
rearranged_df

,police_use_of_force_id,response_date,case_number,problem,subject_race,subject_sex,subject_age,subject_role,primary_offense,type_of_resistance,police_use_of_force_type,force_type_action,subject_injury,neighborhood_id,neighborhood,precinct
0,11224233,2008/01/05 22:57:23+00,08-005343,Suspicious Person,Black,Male,29.0,A,FLEEFT,Fled on Foot,Bodily Force,Punches,Yes,NaN,McKinley,4
1,11224234,2008/01/10 22:21:53+00,08-010291,Motor Vehicle Chase,White,Male,22.0,A,FLEE,Fled in Vehicle,Bodily Force,Punches,Yes,25.0,Central,3
2,11224235,2008/01/25 18:04:32+00,08-024156,Disturbance,Black,Male,40.0,A,DISCON,Commission of Crime,Taser,Firing Darts,No,73.0,Downtown West,1
3,11224236,2008/01/27 02:44:26+00,08-025819,Disturbance,Black,Male,29.0,A,DISCON,Commission of Crime,Chemical Irritant,Crowd Control Mace,NaN,73.0,Downtown West,1
4,11224237,2008/02/10 04:54:24+00,08-039928,Traffic Law Enforcement,Black,Male,28.0,A,FLEE,Fled in Vehicle,Bodily Force,Knees,Yes,73.0,Downtown West,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,2020/01/01 00:00:00+00,20-Lynnhurst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,7.0,Lynnhurst,NaN
30050,11254283,2012/01/01 00:00:00+00,12-St. Anthony East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,St. Anthony East,NaN
30051,11254284,2019/01/01 00:00:00+00,19-Columbia Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,Columbia Park,NaN
30052,11254285,2019/01/01 00:00:00+00,19-Kenwood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,36.0,Kenwood,NaN
30053,11254286,2012/01/01 00:00:00+00,12-Cedar - Isles - Dean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,33.0,Cedar - Isles - Dean,NaN

In [16]:
rearranged_df.dtypes

police_use_of_force_id        int64
response_date                object
case_number                  object
problem                      object
subject_race                 object
subject_sex                  object
subject_age                 float64
subject_role                 object
primary_offense              object
type_of_resistance           object
police_use_of_force_type     object
force_type_action            object
subject_injury               object
neighborhood_id             float64
neighborhood                 object
precinct                     object
dtype: object

In [17]:
rearranged_df.response_date=pd.to_datetime(rearranged_df.response_date)
rearranged_df.head(5)

C:\Users\npren\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,police_use_of_force_id,response_date,case_number,problem,subject_race,subject_sex,subject_age,subject_role,primary_offense,type_of_resistance,police_use_of_force_type,force_type_action,subject_injury,neighborhood_id,neighborhood,precinct
0,11224233,2008-01-05 22:57:23+00:00,08-005343,Suspicious Person,Black,Male,29.0,A,FLEEFT,Fled on Foot,Bodily Force,Punches,Yes,NaN,McKinley,4
1,11224234,2008-01-10 22:21:53+00:00,08-010291,Motor Vehicle Chase,White,Male,22.0,A,FLEE,Fled in Vehicle,Bodily Force,Punches,Yes,25.0,Central,3
2,11224235,2008-01-25 18:04:32+00:00,08-024156,Disturbance,Black,Male,40.0,A,DISCON,Commission of Crime,Taser,Firing Darts,No,73.0,Downtown West,1
3,11224236,2008-01-27 02:44:26+00:00,08-025819,Disturbance,Black,Male,29.0,A,DISCON,Commission of Crime,Chemical Irritant,Crowd Control Mace,NaN,73.0,Downtown West,1
4,11224237,2008-02-10 04:54:24+00:00,08-039928,Traffic Law Enforcement,Black,Male,28.0,A,FLEE,Fled in Vehicle,Bodily Force,Knees,Yes,73.0,Downtown West,1

In [18]:
near_final_police_use_of_force_df = rearranged_df

In [19]:
# Check to see if subject_age field is int
near_final_police_use_of_force_df.dtypes

police_use_of_force_id                    int64
response_date               datetime64[ns, UTC]
case_number                              object
problem                                  object
subject_race                             object
subject_sex                              object
subject_age                             float64
subject_role                             object
primary_offense                          object
type_of_resistance                       object
police_use_of_force_type                 object
force_type_action                        object
subject_injury                           object
neighborhood_id                         float64
neighborhood                             object
precinct                                 object
dtype: object

In [20]:
# Change all NaN(s) in the subject_age field to 0
near_final_police_use_of_force_df['subject_age'] = near_final_police_use_of_force_df['subject_age'].replace(np.nan, 0)

C:\Users\npren\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [21]:
# Confirm task from cell above was completed
near_final_police_use_of_force_df

,police_use_of_force_id,response_date,case_number,problem,subject_race,subject_sex,subject_age,subject_role,primary_offense,type_of_resistance,police_use_of_force_type,force_type_action,subject_injury,neighborhood_id,neighborhood,precinct
0,11224233,2008-01-05 22:57:23+00:00,08-005343,Suspicious Person,Black,Male,29.0,A,FLEEFT,Fled on Foot,Bodily Force,Punches,Yes,NaN,McKinley,4
1,11224234,2008-01-10 22:21:53+00:00,08-010291,Motor Vehicle Chase,White,Male,22.0,A,FLEE,Fled in Vehicle,Bodily Force,Punches,Yes,25.0,Central,3
2,11224235,2008-01-25 18:04:32+00:00,08-024156,Disturbance,Black,Male,40.0,A,DISCON,Commission of Crime,Taser,Firing Darts,No,73.0,Downtown West,1
3,11224236,2008-01-27 02:44:26+00:00,08-025819,Disturbance,Black,Male,29.0,A,DISCON,Commission of Crime,Chemical Irritant,Crowd Control Mace,NaN,73.0,Downtown West,1
4,11224237,2008-02-10 04:54:24+00:00,08-039928,Traffic Law Enforcement,Black,Male,28.0,A,FLEE,Fled in Vehicle,Bodily Force,Knees,Yes,73.0,Downtown West,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,2020-01-01 00:00:00+00:00,20-Lynnhurst,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,7.0,Lynnhurst,NaN
30050,11254283,2012-01-01 00:00:00+00:00,12-St. Anthony East,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,St. Anthony East,NaN
30051,11254284,2019-01-01 00:00:00+00:00,19-Columbia Park,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,Columbia Park,NaN
30052,11254285,2019-01-01 00:00:00+00:00,19-Kenwood,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,36.0,Kenwood,NaN
30053,11254286,2012-01-01 00:00:00+00:00,12-Cedar - Isles - Dean,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,33.0,Cedar - Isles - Dean,NaN

In [22]:
# Convert subject_age field to int64
near_final_police_use_of_force_df['subject_age'] = near_final_police_use_of_force_df['subject_age'].astype(np.int64)

C:\Users\npren\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
# Examine subject_age field to confirm the absence of decimals
near_final_police_use_of_force_df

,police_use_of_force_id,response_date,case_number,problem,subject_race,subject_sex,subject_age,subject_role,primary_offense,type_of_resistance,police_use_of_force_type,force_type_action,subject_injury,neighborhood_id,neighborhood,precinct
0,11224233,2008-01-05 22:57:23+00:00,08-005343,Suspicious Person,Black,Male,29,A,FLEEFT,Fled on Foot,Bodily Force,Punches,Yes,NaN,McKinley,4
1,11224234,2008-01-10 22:21:53+00:00,08-010291,Motor Vehicle Chase,White,Male,22,A,FLEE,Fled in Vehicle,Bodily Force,Punches,Yes,25.0,Central,3
2,11224235,2008-01-25 18:04:32+00:00,08-024156,Disturbance,Black,Male,40,A,DISCON,Commission of Crime,Taser,Firing Darts,No,73.0,Downtown West,1
3,11224236,2008-01-27 02:44:26+00:00,08-025819,Disturbance,Black,Male,29,A,DISCON,Commission of Crime,Chemical Irritant,Crowd Control Mace,NaN,73.0,Downtown West,1
4,11224237,2008-02-10 04:54:24+00:00,08-039928,Traffic Law Enforcement,Black,Male,28,A,FLEE,Fled in Vehicle,Bodily Force,Knees,Yes,73.0,Downtown West,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,2020-01-01 00:00:00+00:00,20-Lynnhurst,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,7.0,Lynnhurst,NaN
30050,11254283,2012-01-01 00:00:00+00:00,12-St. Anthony East,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,St. Anthony East,NaN
30051,11254284,2019-01-01 00:00:00+00:00,19-Columbia Park,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,Columbia Park,NaN
30052,11254285,2019-01-01 00:00:00+00:00,19-Kenwood,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,36.0,Kenwood,NaN
30053,11254286,2012-01-01 00:00:00+00:00,12-Cedar - Isles - Dean,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,33.0,Cedar - Isles - Dean,NaN

In [24]:
# Double check that the subject_age field is int64
near_final_police_use_of_force_df.dtypes

police_use_of_force_id                    int64
response_date               datetime64[ns, UTC]
case_number                              object
problem                                  object
subject_race                             object
subject_sex                              object
subject_age                               int64
subject_role                             object
primary_offense                          object
type_of_resistance                       object
police_use_of_force_type                 object
force_type_action                        object
subject_injury                           object
neighborhood_id                         float64
neighborhood                             object
precinct                                 object
dtype: object

In [25]:
# Adjust punctuation of neighborhood name to match MLS_Neighborhoods.csv
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "St. Anthony West", value ="ST ANTHONY WEST")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "St. Anthony East", value ="ST ANTHONY EAST")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Humboldt Industrial Area", value ="HUMBOLDT INDUST AREA")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Camden Industrial", value ="CAMDEN INDUSTRIAL AREA")        
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "CARAG", value ="South Uptown")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Bryn - Mawr", value ="Bryn Mawr")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Columbia Park", value ="Columbia")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Mid - City Industrial", value ="Mid City Industrial Ar")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "Nicollet Island - East Bank", value ="Nicollet Is/East Bank")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "University of Minnesota", value ="University")
PUOF_final_df = near_final_police_use_of_force_df.replace(to_replace = "McKinley", value ="Mckinley")
PUOF_final_df['neighborhood']= PUOF_final_df['neighborhood'].str.upper()

In [26]:
# Examine edited df
PUOF_final_df

,police_use_of_force_id,response_date,case_number,problem,subject_race,subject_sex,subject_age,subject_role,primary_offense,type_of_resistance,police_use_of_force_type,force_type_action,subject_injury,neighborhood_id,neighborhood,precinct
0,11224233,2008-01-05 22:57:23+00:00,08-005343,Suspicious Person,Black,Male,29,A,FLEEFT,Fled on Foot,Bodily Force,Punches,Yes,NaN,MCKINLEY,4
1,11224234,2008-01-10 22:21:53+00:00,08-010291,Motor Vehicle Chase,White,Male,22,A,FLEE,Fled in Vehicle,Bodily Force,Punches,Yes,25.0,CENTRAL,3
2,11224235,2008-01-25 18:04:32+00:00,08-024156,Disturbance,Black,Male,40,A,DISCON,Commission of Crime,Taser,Firing Darts,No,73.0,DOWNTOWN WEST,1
3,11224236,2008-01-27 02:44:26+00:00,08-025819,Disturbance,Black,Male,29,A,DISCON,Commission of Crime,Chemical Irritant,Crowd Control Mace,NaN,73.0,DOWNTOWN WEST,1
4,11224237,2008-02-10 04:54:24+00:00,08-039928,Traffic Law Enforcement,Black,Male,28,A,FLEE,Fled in Vehicle,Bodily Force,Knees,Yes,73.0,DOWNTOWN WEST,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30049,11254282,2020-01-01 00:00:00+00:00,20-Lynnhurst,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,7.0,LYNNHURST,NaN
30050,11254283,2012-01-01 00:00:00+00:00,12-St. Anthony East,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,ST. ANTHONY EAST,NaN
30051,11254284,2019-01-01 00:00:00+00:00,19-Columbia Park,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,COLUMBIA PARK,NaN
30052,11254285,2019-01-01 00:00:00+00:00,19-Kenwood,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,36.0,KENWOOD,NaN
30053,11254286,2012-01-01 00:00:00+00:00,12-Cedar - Isles - Dean,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,33.0,CEDAR - ISLES - DEAN,NaN

In [27]:
# Create csv out of df
PUOF_final_df.to_csv("../target_files/cleaned_data_police_use_of_force.csv", index=False, header=True)