In [1]:
import pandas as pd
import datetime

In [2]:
#load csv into dataframe
load_csv = ("Source_Data/Police_Use_of_Force_Source_Data.csv")
source_data_df = pd.read_csv(load_csv)
source_data_df.head()

,X,Y,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,Is911Call,PrimaryOffense,SubjectInjury,ForceReportNumber,...,TotalCityCallsForYear,TotalPrecinctCallsForYear,TotalNeighborhoodCallsForYear,CenterGBSID,CenterLatitude,CenterLongitude,CenterX,CenterY,DateAdded,OBJECTID
0,-93.291183,45.018526,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,No,FLEEFT,Yes,1,...,322402,80434.0,4226,18266,45.018526,-93.291183,-10385126.96,5624438.454,2020/06/02 08:18:33+00,1
1,-93.265782,44.943185,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,No,FLEE,Yes,1,...,322402,84018.0,10923,11907,44.943185,-93.265782,-10382299.34,5612581.534,2020/06/02 08:18:33+00,2
2,-93.268029,44.979702,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,No,DISCON,No,1,...,322402,46998.0,23458,18612,44.979702,-93.268029,-10382549.52,5618326.520,2020/06/02 08:18:33+00,3
3,-93.271954,44.982469,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,No,DISCON,NaN,1,...,322402,46998.0,23458,17873,44.982469,-93.271954,-10382986.45,5618762.022,2020/06/02 08:18:33+00,4
4,-93.277025,44.978019,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,No,FLEE,Yes,3,...,322402,46998.0,23458,25506,44.978019,-93.277025,-10383550.97,5618061.726,2020/06/02 08:18:33+00,5

In [3]:
edited_source_data_df = source_data_df.drop(columns = {"X", "Y", "Is911Call", "ForceReportNumber",
                                  "SubjectRoleNumber", "TotalCityCallsForYear",
                                  "TotalPrecinctCallsForYear", "TotalNeighborhoodCallsForYear",
                                  "CenterGBSID", "CenterLatitude", "CenterLongitude",
                                  "CenterX", "CenterY", "DateAdded", "OBJECTID"})

edited_source_data_df.head(5)

,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,PrimaryOffense,SubjectInjury,SubjectRole,ForceType,ForceTypeAction,Race,Sex,EventAge,TypeOfResistance,Precinct,Neighborhood
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West

In [4]:
renamed_columns_df = edited_source_data_df.rename(columns={'PoliceUseOfForceID': 'Police_Use_Of_Force_ID',
                                                          'CaseNumber': 'Case_Number', 'ResponseDate': 'Response_Date',
                                                          'PrimaryOffesne': 'Primary_Offense', 'SubjectInjury': 'Subject_Injury',
                                                          'SubjectRole': 'Subject_Role', 'ForceType': 'Police_Use_Of_Force_Type',
                                                          'ForceTypeAction': 'Force_Type_Action', 'Race': 'Subject_Race', 
                                                          'Sex': 'Subject_Sex', 'EventAge': 'Subject_Event_Age', 'TypeOfResistance': 'Type_Of_Resistance'})

renamed_columns_df.head(5)

,Police_Use_Of_Force_ID,Case_Number,Response_Date,Problem,PrimaryOffense,Subject_Injury,Subject_Role,Police_Use_Of_Force_Type,Force_Type_Action,Subject_Race,Subject_Sex,Subject_Event_Age,Type_Of_Resistance,Precinct,Neighborhood
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West

In [5]:
renamed_columns_df["NBHD_KEY"] = ""

In [6]:
renamed_columns_df.head(5)

,Police_Use_Of_Force_ID,Case_Number,Response_Date,Problem,PrimaryOffense,Subject_Injury,Subject_Role,Police_Use_Of_Force_Type,Force_Type_Action,Subject_Race,Subject_Sex,Subject_Event_Age,Type_Of_Resistance,Precinct,Neighborhood,NBHD_KEY
0,11224233,08-005343,2008/01/05 22:57:23+00,Suspicious Person,FLEEFT,Yes,A,Bodily Force,Punches,Black,Male,29.0,Fled on Foot,4,McKinley,
1,11224234,08-010291,2008/01/10 22:21:53+00,Motor Vehicle Chase,FLEE,Yes,A,Bodily Force,Punches,White,Male,22.0,Fled in Vehicle,3,Central,
2,11224235,08-024156,2008/01/25 18:04:32+00,Disturbance,DISCON,No,A,Taser,Firing Darts,Black,Male,40.0,Commission of Crime,1,Downtown West,
3,11224236,08-025819,2008/01/27 02:44:26+00,Disturbance,DISCON,NaN,A,Chemical Irritant,Crowd Control Mace,Black,Male,29.0,Commission of Crime,1,Downtown West,
4,11224237,08-039928,2008/02/10 04:54:24+00,Traffic Law Enforcement,FLEE,Yes,A,Bodily Force,Knees,Black,Male,28.0,Fled in Vehicle,1,Downtown West,

In [9]:
# Bring in Terrence's nbhd_keys csv
load_second_csv = ("Terrence_CSV/nbhd_keys.csv")
nbhd_keys_df = pd.read_csv(load_second_csv)
nbhd_keys_df.head(5)

   NBHD_KEY  NEIGHBORHOOD  COMMUNITY neighborhood_url
0         1      ARMATAGE  SOUTHWEST         armatage
1         2  EAST HARRIET  SOUTHWEST     east-harriet
2         3        FULTON  SOUTHWEST           fulton
3         4         KENNY  SOUTHWEST            kenny
4         5    KING FIELD  SOUTHWEST       king-field

In [ ]:
left_join_df =